/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataBarang;

/**
 *
 * @author ASUS
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
 import javax.swing.table.DefaultTableModel;
public class GUI_BARANG extends javax.swing.JFrame {

    /**
     * Creates new form GUI_BARANG
     */
    public GUI_BARANG() {
        initComponents();
    Barang obj = new Barang();
txt_kode.setText(obj.getKode());
txt_nama.setText(obj.getNama());
txt_stok.setText(obj.getStok());
txt_harga.setText(obj.getHarga());
   tampil(); 
    }
public Connection conn;
public void koneksi() throws SQLException {
 try {
 conn=null;
 Class.forName("com.mysql.jdbc.Driver");
 conn= 
DriverManager.getConnection("jdbc:mysql://localhost/002_oop?user=root&password=");
 } catch (ClassNotFoundException ex) {
 
Logger.getLogger(GUI_BARANG.class.getName()).log(Level.SEVERE, null, ex);
 } catch (SQLException e) {
 
Logger.getLogger(GUI_BARANG.class.getName()).log(Level.SEVERE, null, e);
 } catch (Exception es) {
 
Logger.getLogger(GUI_BARANG.class.getName()).log(Level.SEVERE, 
null, es);
 }
}
public void tampil() {
 DefaultTableModel tabelhead = new DefaultTableModel();
 tabelhead.addColumn("KODE");
 tabelhead.addColumn("NAMA");
 tabelhead.addColumn("STOK");
 tabelhead.addColumn("HARGA");
 try {
 koneksi();
 String sql = "select * from tb_barang";
 Statement stat = conn.createStatement();
 ResultSet res = stat.executeQuery(sql);
 while(res.next()){
 tabelhead.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3), res.getString(4),});
 }
 table_data.setModel(tabelhead);
 } catch (Exception e) {
 }
 }
public void refresh(){
 new GUI_BARANG().setVisible(true);
 this.setVisible(false);
 }
public void insert(){
 String kode = txt_kode.getText();
 String nama = txt_nama.getText();
 String stok = txt_stok.getText();
 String harga = txt_harga.getText();
 try {
 koneksi();
 Statement statement = conn.createStatement();
 statement.executeUpdate("INSERT INTO tb_barang(kode, nama, stok, harga)"
         + "values('"+kode+"','"+nama+"','"+stok+"','"+harga+"')");
 statement.close();
 JOptionPane.showMessageDialog(null, "Berhasil Memasukan Data Barang!");
 } catch (Exception e) {
 JOptionPane.showMessageDialog(null, "Data Barang Sudah Ada!");
}
 refresh();
  }
public void update(){
 String cari = txt_cari.getText();
 String kode = txt_kode.getText();
 String nama = txt_nama.getText();
 String stok = txt_stok.getText();
 String harga = txt_harga.getText();
 try {
 Statement statement = conn.createStatement();
 statement.executeUpdate("update tb_barang setkode='"+kode+"'," + "nama='"+nama+"',stok='"+stok+"',harga='"+harga+"'where kode = '"+kode+"'");
 statement.close();
 conn.close();
 JOptionPane.showMessageDialog(null, "Update Data Barang!");
 } catch (Exception e) {
 System.out.println("Error : "+e);
 }
 refresh();
 }
public void delete(){
 int ok=JOptionPane.showConfirmDialog(null,"Apakah Anda yakin akan menghapus data?","Konfirmasi",JOptionPane.YES_NO_OPTION);
 if(ok==0){
 try{
 String sql="delete from tb_barang where kode='"+txt_kode.getText()+"'";
 java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
 stmt.executeUpdate();
 JOptionPane.showMessageDialog(null,"Data Berhasil di hapus");
 txt_kode.setText("");
 txt_nama.setText("");
 txt_stok.setText("");
 txt_harga.setText("");
 }catch(Exception e){
 JOptionPane.showMessageDialog(null,"Data gagal di hapus");
 }
 }
 refresh();
}
public void reset()
 {
 txt_kode.setText("");
 txt_nama.setText("");
 txt_stok.setText("");
 txt_harga.setText("");
 }
public void cari(){
 try{
 try (Statement statement = conn.createStatement()) {
 String sql="select * from tb_barang where `kode` like '%"+txt_cari.getText()+"%'";
 ResultSet rs=statement.executeQuery(sql);
if(rs.next())
 {
 txt_kode.setText(rs.getString(1));
txt_nama.setText(rs.getString(2));
txt_stok.setText(rs.getString(3));
txt_harga.setText(rs.getString(4));
 }
 else{
 JOptionPane.showMessageDialog(null, "Barang yang Anda cari tidak ada");
 }
 }
 }catch (Exception ex){
 System.out.println("Error."+ex);
 }
 }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Databarang = new javax.swing.JLabel();
        Databarang1 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        Namabarang = new javax.swing.JLabel();
        Stokbarang = new javax.swing.JLabel();
        Hargabarang = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_stok = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_cari = new javax.swing.JTextField();
        btn_insert = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_data = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        Databarang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Databarang.setText("Data Barang");

        Databarang1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Databarang1.setText("Kode Barang");

        Namabarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Namabarang.setText("Nama Barang");

        Stokbarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Stokbarang.setText("Stok Barang");

        Hargabarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Hargabarang.setText("Harga Barang");

        btn_insert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_insert.setText("Insert");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_cari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_cari.setText("Cari Kode");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_transaksi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_transaksi.setText("Transaksi-->");
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });

        table_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Stok", "Harga"
            }
        ));
        jScrollPane1.setViewportView(table_data);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Databarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Stokbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hargabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(464, 464, 464)
                                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_insert)
                                    .addComponent(btn_update))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_reset)
                                    .addComponent(btn_delete))
                                .addGap(126, 126, 126))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Databarang, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(306, 306, 306)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cari)
                    .addComponent(btn_transaksi))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Databarang1)
                            .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cari)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Databarang)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Namabarang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Stokbarang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hargabarang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_transaksi)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delete)
                            .addComponent(btn_insert))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_reset)
                            .addComponent(btn_update))
                        .addGap(0, 10, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
insert();     
Barang obj = new Barang();
 
 obj.setKode(txt_kode.getText());
 obj.setNama(txt_nama.getText());
 obj.setStok(txt_stok.getText());
 obj.setHarga(txt_harga.getText());
 
 
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
delete();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
       update();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
       reset(); // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
cari();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
GUI_TRANSAKSI obj = new GUI_TRANSAKSI();
 obj.show();
 this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_transaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_BARANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_BARANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_BARANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_BARANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_BARANG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Databarang;
    private javax.swing.JLabel Databarang1;
    private javax.swing.JLabel Hargabarang;
    private javax.swing.JLabel Namabarang;
    private javax.swing.JLabel Stokbarang;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JButton btn_update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_data;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_stok;
    // End of variables declaration//GEN-END:variables
}
